[project]
name = "to-do-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Abdurahman Mohammed", email = "abdurahmanmoh.3@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "rich>=15.0.0",
]

[project.scripts]
to-do-app = "to_do_app:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
